use crate::{
    auth::middleware::JwtMiddleware,
    reports::{handlers, legal, pos_metrics},
};
use actix_web::web;
use sqlx::PgPool;

/// `read_pool` overrides the app-wide write pool for THIS scope only: every reports
/// handler extracts `web::Data<PgPool>`, and actix resolves scope-level `app_data`
/// ahead of app-level, so they all run against the read replica (when
/// `READ_DATABASE_URL` is set) with zero per-handler changes. Reports are read-only.
pub fn configure(cfg: &mut web::ServiceConfig, read_pool: web::Data<PgPool>) {
    cfg.service(
        web::scope("/reports")
            .app_data(read_pool)
            .wrap(JwtMiddleware)
            .route(
                "/tills/{till_id}/summary",
                web::get().to(handlers::till_summary),
            )
            .route(
                "/tills/{till_id}/deductions",
                web::get().to(handlers::till_deductions),
            )
            .route(
                "/shifts/{shift_id}/summary",
                web::get().to(handlers::shift_summary),
            )
            .route(
                "/shifts/{shift_id}/deductions",
                web::get().to(handlers::shift_deductions),
            )
            .route(
                "/branches/{branch_id}/sales",
                web::get().to(handlers::branch_sales),
            )
            .route(
                "/branches/{branch_id}/pos-metrics",
                web::get().to(pos_metrics::branch_pos_metrics),
            )
            .route(
                "/branches/{branch_id}/sales/timeseries",
                web::get().to(handlers::branch_sales_timeseries),
            )
            .route(
                "/branches/{branch_id}/sales/peak-hours",
                web::get().to(handlers::branch_sales_peak_hours),
            )
            .route(
                "/branches/{branch_id}/sales/peak-days",
                web::get().to(handlers::branch_sales_peak_days),
            )
            .route(
                "/branches/{branch_id}/tellers",
                web::get().to(handlers::branch_teller_stats),
            )
            .route(
                "/branches/{branch_id}/tills",
                web::get().to(handlers::branch_till_sessions),
            )
            .route(
                "/branches/{branch_id}/waiters",
                web::get().to(handlers::branch_waiter_stats),
            )
            .route(
                "/branches/{branch_id}/addons",
                web::get().to(handlers::branch_addon_sales),
            )
            .route(
                "/branches/{branch_id}/stock",
                web::get().to(handlers::branch_stock),
            )
            .route(
                "/branches/{branch_id}/bundles",
                web::get().to(handlers::branch_bundle_sales),
            )
            .route(
                "/branches/{branch_id}/items-combined",
                web::get().to(handlers::branch_combined_item_sales),
            )
            .route(
                "/branches/{branch_id}/inventory-valuation",
                web::get().to(handlers::branch_inventory_valuation),
            )
            .route(
                "/branches/{branch_id}/consumption",
                web::get().to(handlers::branch_consumption),
            )
            .route(
                "/branches/{branch_id}/waste-report",
                web::get().to(handlers::branch_waste_report),
            )
            .route(
                "/branches/{branch_id}/shrinkage",
                web::get().to(handlers::branch_shrinkage),
            )
            .route(
                "/branches/{branch_id}/low-stock",
                web::get().to(handlers::branch_low_stock),
            )
            .route(
                "/branches/{branch_id}/delivery-sales",
                web::get().to(handlers::branch_delivery_sales),
            )
            .route(
                "/branches/{branch_id}/channel-breakdown",
                web::get().to(handlers::branch_channel_breakdown),
            )
            .route(
                "/branches/{branch_id}/supplier-spend",
                web::get().to(handlers::branch_supplier_spend),
            )
            .route(
                "/branches/{branch_id}/po-lead-time",
                web::get().to(handlers::branch_po_lead_time),
            )
            .route(
                "/branches/{branch_id}/material-cost-trend",
                web::get().to(handlers::branch_material_cost_trend),
            )
            .route(
                "/orgs/{org_id}/comparison",
                web::get().to(handlers::org_branch_comparison),
            )
            .route(
                "/orgs/{org_id}/tax",
                web::get().to(handlers::org_tax_report),
            )
            .route(
                "/orgs/{org_id}/refunds-audit",
                web::get().to(legal::refunds_audit),
            )
            .route(
                "/orgs/{org_id}/voids-audit",
                web::get().to(legal::voids_audit),
            )
            .route(
                "/orgs/{org_id}/discounts-audit",
                web::get().to(legal::discounts_audit),
            )
            .route(
                "/orgs/{org_id}/waivers-audit",
                web::get().to(legal::waivers_audit),
            )
            .route(
                "/orgs/{org_id}/price-overrides",
                web::get().to(legal::price_overrides),
            )
            .route(
                "/orgs/{org_id}/manual-deductions-audit",
                web::get().to(legal::manual_deductions_audit),
            )
            .route(
                "/orgs/{org_id}/deduction-overrides-audit",
                web::get().to(legal::deduction_overrides_audit),
            )
            .route(
                "/orgs/{org_id}/loyalty-adjustments-audit",
                web::get().to(legal::loyalty_adjustments_audit),
            )
            .route(
                "/orgs/{org_id}/attendance-corrections-audit",
                web::get().to(legal::attendance_corrections_audit),
            )
            .route(
                "/orgs/{org_id}/inventory-valuation",
                web::get().to(handlers::org_inventory_valuation),
            )
            .route(
                "/orgs/{org_id}/low-stock",
                web::get().to(handlers::org_low_stock),
            )
            .route(
                "/orgs/{org_id}/consumption",
                web::get().to(handlers::org_consumption),
            )
            .route(
                "/orgs/{org_id}/waste-report",
                web::get().to(handlers::org_waste_report),
            )
            .route(
                "/orgs/{org_id}/shrinkage",
                web::get().to(handlers::org_shrinkage),
            )
            .route(
                "/orgs/{org_id}/supplier-spend",
                web::get().to(handlers::org_supplier_spend),
            )
            .route(
                "/orgs/{org_id}/po-lead-time",
                web::get().to(handlers::org_po_lead_time),
            )
            .route(
                "/orgs/{org_id}/material-cost-trend",
                web::get().to(handlers::org_material_cost_trend),
            ),
    );
}
