#!/usr/bin/env python3
"""Copy push-notification words from madar-core's i18n table into
src/push/words.rs, for every app (Dawam today; a future app adds its own
prefix below). The phone's words are the source of truth; a push is shown by
the OS while the app is closed, so the server needs its own copy too.

    python3 scripts/sync_push_words.py [../madar/rust-core/crates/madar-core/src/i18n.rs]
"""
import os, re, sys

here = os.path.dirname(os.path.abspath(__file__))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    here, '../../madar/rust-core/crates/madar-core/src/i18n.rs')
text = open(src).read()

# Key prefixes copied in, one row per app. Add a new app's prefixes here when
# it starts sending pushes.
PREFIXES = (r'staff\.n_[a-z_]+', r'staff\.kind_[a-z_]+', r'staff\.dawam_by_madar', r'push\.[a-z_]+')
pat = re.compile(r'^\s*"(' + '|'.join(PREFIXES) + r')" => "((?:[^"\\]|\\.)*)",', re.M)

def block(fn):
    a = text.index(f'fn {fn}(key: &str)')
    b = text.index('_ => return None', a)
    return dict(pat.findall(text[a:b]))

en, ar = block('en'), block('ar')
missing = sorted(set(en) ^ set(ar))
if missing:
    sys.exit(f'only in one language: {missing}')
rows = ''.join(f'    ("{k}", "{en[k]}", "{ar[k]}"),\n' for k in sorted(en))
out = os.path.join(here, '../src/push/words.rs')
open(out, 'w').write(
    '//! GENERATED by scripts/sync_push_words.py from madar-core\'s i18n.rs — do\n'
    '//! not edit. The words a push shows while the app is closed.\n\n'
    '/// (key, English, Arabic)\n'
    'pub const WORDS: &[(&str, &str, &str)] = &[\n' + rows + '];\n')
print(f'wrote {len(en)} words to {os.path.relpath(out)}')
