//! GENERATED by scripts/sync_push_words.py from madar-core's i18n.rs — do
//! not edit. The words a push shows while the app is closed.

/// (key, English, Arabic)
pub const WORDS: &[(&str, &str, &str)] = &[
    ("staff.dawam_by_madar", "Dawam by Madar", "دوام بواسطة مدار"),
    ("staff.kind_correction", "Correction", "تصحيح"),
    ("staff.kind_cover", "Cover", "تغطية"),
    (
        "staff.kind_early_departure",
        "Early departure",
        "انصراف بدري",
    ),
    ("staff.kind_excuse", "Excuse", "إذن"),
    ("staff.kind_late_arrival", "Late arrival", "تأخير"),
    ("staff.kind_leave", "Leave", "إجازة"),
    ("staff.kind_mission", "Mission", "مأمورية"),
    ("staff.kind_open_shift", "Open shift", "وردية متاحة"),
    ("staff.kind_overtime", "Overtime", "وقت إضافي"),
    ("staff.kind_salary_advance", "Salary advance", "سلفة"),
    ("staff.kind_swap", "Swap", "تبديل"),
    (
        "staff.n_adjustment_approved",
        "The pay line for {name} was approved",
        "البند بتاع {name} اتوافق عليه",
    ),
    (
        "staff.n_adjustment_pending",
        "{by} added a pay line for {name} over the limit ({amount}) — approve it",
        "{by} ضاف بند لـ{name} فوق الحد ({amount}) — وافق عليه",
    ),
    (
        "staff.n_adjustment_rejected",
        "The pay line for {name} was declined",
        "البند بتاع {name} اترفض",
    ),
    (
        "staff.n_advance_approved",
        "Your salary advance of {amount} was approved",
        "السلفة بتاعتك ({amount}) اتوافق عليها",
    ),
    (
        "staff.n_advance_rejected",
        "Your salary advance was declined",
        "السلفة بتاعتك اترفضت",
    ),
    (
        "staff.n_bonus_added",
        "A bonus was added: {reason} ({amount})",
        "اتضافت مكافأة: {reason} ({amount})",
    ),
    (
        "staff.n_charge_phone",
        "Your battery is low. Charge your phone so your shift keeps being recorded.",
        "البطارية واطية. اشحن موبايلك عشان ورديتك تفضل متسجلة.",
    ),
    (
        "staff.n_claim",
        "{name} claimed the open shift on {date} — approve it",
        "{name} حجز الوردية المتاحة يوم {date} — وافق عليها",
    ),
    (
        "staff.n_claim_approved",
        "The shift on {date} is yours",
        "وردية يوم {date} بقت بتاعتك",
    ),
    (
        "staff.n_claim_rejected",
        "Your claim for {date} was declined",
        "حجزك ليوم {date} اترفض",
    ),
    (
        "staff.n_cover",
        "{name} is covering {owner}'s shift — confirm to pay it",
        "{name} بيغطي وردية {owner} — أكّد عشان تتدفع",
    ),
    (
        "staff.n_cover_confirmed",
        "Your cover shift was confirmed — it will be paid",
        "التغطية بتاعتك اتأكدت — هتتدفع",
    ),
    (
        "staff.n_cover_rejected",
        "Your cover shift was not confirmed",
        "التغطية بتاعتك ما اتأكدتش",
    ),
    (
        "staff.n_deduction_added",
        "A deduction was added: {reason} ({amount})",
        "اتضاف خصم: {reason} ({amount})",
    ),
    (
        "staff.n_flag_cover",
        "{name} opened a cover shift",
        "{name} فتح وردية تغطية",
    ),
    (
        "staff.n_flag_left_mid_shift",
        "{name} left the branch mid-shift ({minutes} min away)",
        "{name} خرج من الفرع أثناء الوردية ({minutes} د برّه)",
    ),
    (
        "staff.n_flag_new_phone",
        "{name} signed in on a new phone",
        "{name} سجّل دخول من موبايل جديد",
    ),
    (
        "staff.n_flag_phone_died",
        "{name}'s phone likely died on shift (battery was low)",
        "موبايل {name} غالبًا فصل شحن وهو في الوردية (البطارية كانت واطية)",
    ),
    (
        "staff.n_flag_suspicious",
        "{name}'s location looks spoofed",
        "موقع {name} شكله مزيّف",
    ),
    (
        "staff.n_flag_time_unverified",
        "{name}'s punch time couldn't be verified",
        "وقت تسجيل {name} ما اتأكدش",
    ),
    (
        "staff.n_flag_tracking_off",
        "{name} is on shift with tracking off",
        "{name} في الوردية والتتبع مقفول",
    ),
    (
        "staff.n_new_phone",
        "{name} moved to a new phone ({device}); the old one is signed out",
        "{name} نقل على موبايل جديد ({device})؛ القديم اتقفل",
    ),
    (
        "staff.n_open_shift",
        "An open shift on {date} was posted — claim it in Shifts",
        "في وردية متاحة يوم {date} — احجزها من الورديات",
    ),
    (
        "staff.n_overtime",
        "{name} worked {minutes} min overtime — approve it",
        "{name} اشتغل {minutes} د إضافي — وافق عليه",
    ),
    (
        "staff.n_overtime_approved",
        "Your {minutes} min overtime was approved",
        "الوقت الإضافي بتاعك ({minutes} د) اتوافق عليه",
    ),
    (
        "staff.n_overtime_rejected",
        "Your {minutes} min overtime was declined",
        "الوقت الإضافي بتاعك ({minutes} د) اترفض",
    ),
    (
        "staff.n_paid",
        "Your pay is marked paid ({method})",
        "مرتبك اتعلّم إنه اتدفع ({method})",
    ),
    (
        "staff.n_punched_for_you",
        "{name} punched for you: {reason}",
        "{name} سجّل ليك: {reason}",
    ),
    (
        "staff.n_request",
        "{name}: new {kind} request for {date}",
        "{name}: طلب {kind} جديد ليوم {date}",
    ),
    (
        "staff.n_request_approved",
        "Your {kind} request for {date} was approved",
        "طلب {kind} بتاعك ليوم {date} اتوافق عليه",
    ),
    (
        "staff.n_request_rejected",
        "Your {kind} request for {date} was declined",
        "طلب {kind} بتاعك ليوم {date} اترفض",
    ),
    (
        "staff.n_shift_changed",
        "Your shift on {date} changed",
        "ورديتك يوم {date} اتغيرت",
    ),
    (
        "staff.n_swap_agreed",
        "{name} agreed to swap — waiting for the manager",
        "{name} وافق على التبديل — مستني المدير",
    ),
    (
        "staff.n_swap_approved",
        "Your shift swap was approved",
        "تبديل الوردية اتوافق عليه",
    ),
    (
        "staff.n_swap_asked",
        "{name} wants to swap a shift with you",
        "{name} عايز يبدّل وردية معاك",
    ),
    (
        "staff.n_swap_declined",
        "{name} declined the swap",
        "{name} رفض التبديل",
    ),
    (
        "staff.n_swap_pending",
        "A shift swap waits for your approval",
        "تبديل وردية مستني موافقتك",
    ),
    (
        "staff.n_swap_rejected",
        "Your shift swap was declined",
        "تبديل الوردية اترفض",
    ),
    (
        "staff.n_week_published",
        "The roster for the week of {date} is published",
        "جدول أسبوع {date} اتنشر",
    ),
];
